services:
  api:
    build:
      context: .
      dockerfile: config/dockerfiles/dockerfile-ruby
    ports:
      - '3001:3000'
    tty: true
    stdin_open: true
    env_file:
      - config/environment/rails.local.env
      - config/environment/db.env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./services/api:/app
    depends_on:
      - postgres

  web:
    build:
      context: .
      dockerfile: config/dockerfiles/dockerfile-nextjs
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    env_file:
      - config/environment/nextjs.local.env
    volumes:
      - ./services/web:/app
    depends_on:
      - api

  postgres:
    image: postgres:15
    env_file:
      - config/environment/db.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
