family_category = Category.find_by(name: 'Individual & Family Portraits')
engagement_category = Category.find_by(name: 'Engagement & Couples Photography')
corporate_category = Category.find_by(name: 'Corporate & Commercial Photography')
product_category = Category.find_by(name: 'Product Photography')
pet_category = Category.find_by(name: 'Pet & Animal Photography')
event_category = Category.find_by(name: 'Event Photography')
graduation_category = Category.find_by(name: 'Graduation & Senior Portraits')

Addon.create(name: 'Additional pet', price: 50, category: pet_category)
Addon.create(name: 'Additional location', price: 75, category: pet_category)
Addon.create(name: 'Extra digital images', price: 15, category: pet_category)
Addon.create(name: 'Custom pet portrait', price: 100, category: pet_category)
Addon.create(name: 'Pet photo album', price: 200, category: pet_category)

Addon.create(name: 'Additional outfit', price: 50, category: graduation_category)
Addon.create(name: 'Additional location', price: 75, category: graduation_category)
Addon.create(name: 'Extra digital images', price: 15, category: graduation_category)
Addon.create(name: 'Graduation announcements (set of 25)', price: 75, category: graduation_category)
Addon.create(name: 'Cap and gown mini-session', price: 100, category: graduation_category)

Addon.create(name: 'Additional family members (beyond package limit)', price: 25, category: family_category)
Addon.create(name: 'Additional location', price: 75, category: family_category)
Addon.create(name: 'Extra digital images', price: 15, category: family_category)
Addon.create(name: 'Family photo album', price: 250, category: family_category)
Addon.create(name: 'Holiday card design', price: 75, category: family_category)

Addon.create(name: 'Additional hour', price: 150, category: engagement_category)
Addon.create(name: 'Additional location', price: 75, category: engagement_category)
Addon.create(name: 'Extra digital images', price: 15, category: engagement_category)
Addon.create(name: 'Save the Date design', price: 250, category: engagement_category)
Addon.create(name: 'Engagement guest book', price: 75, category: engagement_category)

Addon.create(name: 'Additional employee headshots', price: 50, category: corporate_category)
Addon.create(name: 'Location Change', price: 100, category: corporate_category)
Addon.create(name: 'Rush Delivery', price: 200, category: corporate_category)
Addon.create(name: 'Social Media Content Package', price: 300, category: corporate_category)

Addon.create(name: 'Additional hour of coverage', price: 200, category: event_category)
Addon.create(name: 'Second photographer (4 hours)', price: 400, category: event_category)
Addon.create(name: 'Rush delivery (48 hours)', price: 250, category: event_category)
Addon.create(name: 'Professional event album (30 pages)', price: 450, category: event_category)
Addon.create(name: 'Custom branded photo backdrop', price: 300, category: event_category)

Addon.create(name: 'Additional products', price: 300, category: product_category)
Addon.create(name: '360° product rotation', price: 750, category: product_category)
Addon.create(name: 'Lifestyle/context shots', price: 100, category: product_category)
Addon.create(name: 'Product video clips (15 sec)', price: 150, category: product_category)
Addon.create(name: 'Amazon/E-commerce specific requirements', price: 500, category: product_category)
