family_category = Category.find_by(name: 'Individual & Family Portraits')
engagement_category = Category.find_by(name: 'Engagement & Couples Photography')
corporate_category = Category.find_by(name: 'Corporate & Commercial Photography')
product_category = Category.find_by(name: 'Product Photography')
pet_category = Category.find_by(name: 'Pet & Animal Photography')
event_category = Category.find_by(name: 'Event Photography')
graduation_category = Category.find_by(name: 'Graduation & Senior Portraits')

Collection.create(name: 'Leah Newhouse Wedding Ceremony', category: engagement_category)
Collection.create(name: 'Trung Nguyen Wedding Reception', category: engagement_category)
Collection.create(name: 'Vika Glitter Portraits', category: family_category)
Collection.create(name: 'The Heyday Family', category: family_category)
Collection.create(name: 'Michaela and The Babies', category: pet_category)
Collection.create(name: 'RDNE Graduation Celebration', category: graduation_category)
Collection.create(name: 'CP Corporate', category: corporate_category)
Collection.create(name: 'The z500x Camera', category: product_category)
Collection.create(name: "Maria kurnyk's Bakery", category: product_category)
Collection.create(name: 'Thibault Trillet Concert', category: event_category)
