ln_wedding_collection = Collection.find_by(name: 'Leah Newhouse Wedding Ceremony')
tn_wedding_collection = Collection.find_by(name: 'Trung Nguyen Wedding Reception')
vg_portrait_collection = Collection.find_by(name: 'Vika Glitter Portraits')
hd_family_collection = Collection.find_by(name: 'The Heyday Family')
m_pet_collection = Collection.find_by(name: 'Michaela and The Babies')
rdne_graduation_collection = Collection.find_by(name: 'RDNE Graduation Celebration')
cp_collection = Collection.find_by(name: 'CP Corporate')
camera_product_collection = Collection.find_by(name: 'The z500x Camera')
mk_bakery_collection = Collection.find_by(name: "Maria kurnyk's Bakery")
tt_concert_collection = Collection.find_by(name: 'Thibault Trillet Concert')

family_category = Category.find_by(name: 'Individual & Family Portraits')
engagement_category = Category.find_by(name: 'Engagement & Couples Photography')
corporate_category = Category.find_by(name: 'Corporate & Commercial Photography')
product_category = Category.find_by(name: 'Product Photography')
pet_category = Category.find_by(name: 'Pet & Animal Photography')
event_category = Category.find_by(name: 'Event Photography')
graduation_category = Category.find_by(name: 'Graduation & Senior Portraits')

Photo.create(file_key: 'leah-newhouse-wedding-1.jpg', collection: ln_wedding_collection, highlighted: true)
Photo.create(file_key: 'leah-newhouse-wedding-2.jpg', collection: ln_wedding_collection, highlighted: false)
Photo.create(file_key: 'leah-newhouse-wedding-3.jpg', collection: ln_wedding_collection, highlighted: false)
Photo.create(file_key: 'leah-newhouse-wedding-4.jpg', collection: ln_wedding_collection, highlighted: false)
Photo.create(file_key: 'leah-newhouse-wedding-5.jpg', collection: ln_wedding_collection, highlighted: false)
Photo.create(file_key: 'leah-newhouse-wedding-6.jpg', collection: ln_wedding_collection, highlighted: false)
Photo.create(file_key: 'leah-newhouse-wedding-7.jpg', collection: ln_wedding_collection, highlighted: false)
p1 = Photo.create(file_key: 'leah-newhouse-wedding-8.jpg', collection: ln_wedding_collection, highlighted: false)
Photo.create(file_key: 'leah-newhouse-wedding-9.jpg', collection: ln_wedding_collection, highlighted: false)
engagement_category.update(featured_photo_id: p1.id)

Photo.create(file_key: 'Trung-Nguyen-wedding-1.jpg', collection: tn_wedding_collection, highlighted: true)
Photo.create(file_key: 'Trung-Nguyen-wedding-2.jpg', collection: tn_wedding_collection, highlighted: false)
Photo.create(file_key: 'Trung-Nguyen-wedding-3.jpg', collection: tn_wedding_collection, highlighted: false)
Photo.create(file_key: 'Trung-Nguyen-wedding-4.jpg', collection: tn_wedding_collection, highlighted: false)
Photo.create(file_key: 'Trung-Nguyen-wedding-5.jpg', collection: tn_wedding_collection, highlighted: false)
Photo.create(file_key: 'Trung-Nguyen-wedding-6.jpg', collection: tn_wedding_collection, highlighted: false)
Photo.create(file_key: 'Trung-Nguyen-wedding-7.jpg', collection: tn_wedding_collection, highlighted: false)
Photo.create(file_key: 'Trung-Nguyen-wedding-8.jpg', collection: tn_wedding_collection, highlighted: false)
Photo.create(file_key: 'Trung-Nguyen-wedding-9.jpg', collection: tn_wedding_collection, highlighted: false)
Photo.create(file_key: 'Trung-Nguyen-wedding-10.jpg', collection: tn_wedding_collection, highlighted: false)
Photo.create(file_key: 'Trung-Nguyen-wedding-11.jpg', collection: tn_wedding_collection, highlighted: false)

Photo.create(file_key: 'Vika-Glitter-single-1.jpg', collection: vg_portrait_collection, highlighted: true)
Photo.create(file_key: 'Vika-Glitter-single-2.jpg', collection: vg_portrait_collection, highlighted: false)
Photo.create(file_key: 'Vika-Glitter-single-3.jpg', collection: vg_portrait_collection, highlighted: false)
Photo.create(file_key: 'Vika-Glitter-single-4.jpg', collection: vg_portrait_collection, highlighted: false)
Photo.create(file_key: 'Vika-Glitter-single-5.jpg', collection: vg_portrait_collection, highlighted: false)
Photo.create(file_key: 'Vika-Glitter-single-6.jpg', collection: vg_portrait_collection, highlighted: false)

Photo.create(file_key: 'Heyday-family-1.jpg', collection: hd_family_collection, highlighted: true)
Photo.create(file_key: 'Heyday-family-2.jpg', collection: hd_family_collection, highlighted: false)
Photo.create(file_key: 'Heyday-family-3.jpg', collection: hd_family_collection, highlighted: false)
Photo.create(file_key: 'Heyday-family-4.jpg', collection: hd_family_collection, highlighted: false)
p2 = Photo.create(file_key: 'Heyday-family-5.jpg', collection: hd_family_collection, highlighted: false)
family_category.update(featured_photo_id: p2.id)

Photo.create(file_key: 'Cong-H-Pet-1.jpg', collection: m_pet_collection, highlighted: true)
Photo.create(file_key: 'Cong-H-Pet-2.jpg', collection: m_pet_collection, highlighted: false)
Photo.create(file_key: 'Cong-H-Pet-3.jpg', collection: m_pet_collection, highlighted: false)
p3 = Photo.create(file_key: 'Cong-H-Pet-4.jpg', collection: m_pet_collection, highlighted: false)
Photo.create(file_key: 'Cong-H-Pet-5.jpg', collection: m_pet_collection, highlighted: false)
Photo.create(file_key: 'Cong-H-Pet-6.jpg', collection: m_pet_collection, highlighted: false)
Photo.create(file_key: 'Cong-H-Pet-7.jpg', collection: m_pet_collection, highlighted: false)
Photo.create(file_key: 'Cong-H-Pet-8.jpg', collection: m_pet_collection, highlighted: false)
Photo.create(file_key: 'Cong-H-Pet-9.jpg', collection: m_pet_collection, highlighted: false)
Photo.create(file_key: 'Cong-H-Pet-10.jpg', collection: m_pet_collection, highlighted: false)
Photo.create(file_key: 'Cong-H-Pet-11.jpg', collection: m_pet_collection, highlighted: false)
Photo.create(file_key: 'Cong-H-Pet-12.jpg', collection: m_pet_collection, highlighted: false)
Photo.create(file_key: 'Cong-H-Pet-13.jpg', collection: m_pet_collection, highlighted: false)
Photo.create(file_key: 'Cong-H-Pet-14.jpg', collection: m_pet_collection, highlighted: false)
pet_category.update(featured_photo_id: p3.id)

Photo.create(file_key: 'RDNE-gradutation-1.jpg', collection: rdne_graduation_collection, highlighted: true)
Photo.create(file_key: 'RDNE-gradutation-2.jpg', collection: rdne_graduation_collection, highlighted: false)
Photo.create(file_key: 'RDNE-gradutation-3.jpg', collection: rdne_graduation_collection, highlighted: false)
Photo.create(file_key: 'RDNE-gradutation-4.jpg', collection: rdne_graduation_collection, highlighted: false)
Photo.create(file_key: 'RDNE-gradutation-5.jpg', collection: rdne_graduation_collection, highlighted: false)
Photo.create(file_key: 'RDNE-gradutation-6.jpg', collection: rdne_graduation_collection, highlighted: false)
Photo.create(file_key: 'RDNE-gradutation-7.jpg', collection: rdne_graduation_collection, highlighted: false)
Photo.create(file_key: 'RDNE-gradutation-8.jpg', collection: rdne_graduation_collection, highlighted: false)
p4 = Photo.create(file_key: 'RDNE-gradutation-9.jpg', collection: rdne_graduation_collection, highlighted: false)
graduation_category.update(featured_photo_id: p4.id)

Photo.create(file_key: 'CP-corporate-1.jpg', collection: cp_collection, highlighted: false)
Photo.create(file_key: 'CP-corporate-2.jpg', collection: cp_collection, highlighted: false)
Photo.create(file_key: 'CP-corporate-4.jpg', collection: cp_collection, highlighted: false)
Photo.create(file_key: 'CP-corporate-5.jpg', collection: cp_collection, highlighted: false)
p5 = Photo.create(file_key: 'CP-corporate-6.jpg', collection: cp_collection, highlighted: false)
Photo.create(file_key: 'CP-corporate-7.jpg', collection: cp_collection, highlighted: true)
corporate_category.update(featured_photo_id: p5.id)

Photo.create(file_key: 'camera-product-1.jpg', collection: camera_product_collection, highlighted: false)
Photo.create(file_key: 'camera-product-2.jpg', collection: camera_product_collection, highlighted: false)
Photo.create(file_key: 'camera-product-3.jpg', collection: camera_product_collection, highlighted: false)
Photo.create(file_key: 'camera-product-4.jpg', collection: camera_product_collection, highlighted: false)
p6 = Photo.create(file_key: 'camera-product-5.jpg', collection: camera_product_collection, highlighted: false)
Photo.create(file_key: 'camera-product-6.jpg', collection: camera_product_collection, highlighted: false)
Photo.create(file_key: 'camera-product-7.jpg', collection: camera_product_collection, highlighted: true)
Photo.create(file_key: 'camera-product-8.jpg', collection: camera_product_collection, highlighted: false)
Photo.create(file_key: 'camera-product-9.jpg', collection: camera_product_collection, highlighted: false)
product_category.update(featured_photo_id: p6.id)

Photo.create(file_key: 'Mariana-Kurnyk-bakery-1.jpg', collection: mk_bakery_collection, highlighted: false)
Photo.create(file_key: 'Mariana-Kurnyk-bakery-2.jpg', collection: mk_bakery_collection, highlighted: false)
Photo.create(file_key: 'Mariana-Kurnyk-bakery-3.jpg', collection: mk_bakery_collection, highlighted: false)
Photo.create(file_key: 'Mariana-Kurnyk-bakery-4.jpg', collection: mk_bakery_collection, highlighted: false)
Photo.create(file_key: 'Mariana-Kurnyk-bakery-5.jpg', collection: mk_bakery_collection, highlighted: true)
Photo.create(file_key: 'Mariana-Kurnyk-bakery-6.jpg', collection: mk_bakery_collection, highlighted: false)
Photo.create(file_key: 'Mariana-Kurnyk-bakery-7.jpg', collection: mk_bakery_collection, highlighted: false)
Photo.create(file_key: 'Mariana-Kurnyk-bakery-8.jpg', collection: mk_bakery_collection, highlighted: false)
Photo.create(file_key: 'Mariana-Kurnyk-bakery-9.jpg', collection: mk_bakery_collection, highlighted: true)

Photo.create(file_key: 'Thibault-Trillet-event-1.jpg', collection: tt_concert_collection, highlighted: false)
Photo.create(file_key: 'Thibault-Trillet-event-2.jpg', collection: tt_concert_collection, highlighted: false)
Photo.create(file_key: 'Thibault-Trillet-event-3.jpg', collection: tt_concert_collection, highlighted: true)
Photo.create(file_key: 'Thibault-Trillet-event-4.jpg', collection: tt_concert_collection, highlighted: false)
Photo.create(file_key: 'Thibault-Trillet-event-5.jpg', collection: tt_concert_collection, highlighted: false)
Photo.create(file_key: 'Thibault-Trillet-event-6.jpg', collection: tt_concert_collection, highlighted: false)
p7 = Photo.create(file_key: 'Thibault-Trillet-event-7.jpg', collection: tt_concert_collection, highlighted: true)
event_category.update(featured_photo_id: p7.id)
